import type {
  RuntimeFileCollectRequest,
  V1File,
  V1FileDeleteResponse,
  V1FilesListQuery,
  V1FileUpdateRequest,
  V1Invocation,
  V1InvocationResponse,
  V1InvocationSummary,
  V1InvocationWaitRequest,
  V1InvocationWaitResponse,
  V1RunInvocationsListQuery,
  V1Runtime,
  V1RuntimeCreateRequest,
  V1RuntimeListQuery,
  V1RuntimeFileStageRequest,
  V1RuntimeRunListQuery,
  V1RuntimeStagedFile,
  V1RuntimeStartResponse,
  V1Run,
  V1RunEventsListQuery,
  V1RunFilesExportRequest,
  V1RunFilesListQuery,
  V1RunLiveRequest,
  V1RunLiveResponse,
  V1RunRecordingRequest,
  V1RunRecordingResponse,
  V1Space,
  V1SpaceCreateRequest,
  V1SpaceEnvironment,
  V1SpaceEnvironmentUpdateRequest,
  V1SpaceRuntimeCreateRequest,
  V1SpaceUpdateRequest,
} from '../../../packages/api-contracts/src/index.js';
import type {
  V1File as SdkV1File,
  V1FileDeleteResponse as SdkV1FileDeleteResponse,
  V1FilesListQuery as SdkV1FilesListQuery,
  V1FileUpdateRequest as SdkV1FileUpdateRequest,
  V1Invocation as SdkV1Invocation,
  V1InvocationResponse as SdkV1InvocationResponse,
  V1InvocationSummary as SdkV1InvocationSummary,
  V1InvocationWaitRequest as SdkV1InvocationWaitRequest,
  V1InvocationWaitResponse as SdkV1InvocationWaitResponse,
  V1RunInvocationsListQuery as SdkV1RunInvocationsListQuery,
  V1Runtime as SdkV1Runtime,
  V1RuntimeCreateRequest as SdkV1RuntimeCreateRequest,
  V1RuntimeListQuery as SdkV1RuntimeListQuery,
  V1RuntimeFileCollectRequest as SdkV1RuntimeFileCollectRequest,
  V1RuntimeFileStageRequest as SdkV1RuntimeFileStageRequest,
  V1RuntimeRunListQuery as SdkV1RuntimeRunListQuery,
  V1RuntimeStagedFile as SdkV1RuntimeStagedFile,
  V1RuntimeStartResponse as SdkV1RuntimeStartResponse,
  V1Run as SdkV1Run,
  V1RunEventsListQuery as SdkV1RunEventsListQuery,
  V1RunFilesExportRequest as SdkV1RunFilesExportRequest,
  V1RunFilesListQuery as SdkV1RunFilesListQuery,
  V1RunLiveRequest as SdkV1RunLiveRequest,
  V1RunLiveResponse as SdkV1RunLiveResponse,
  V1RunRecordingRequest as SdkV1RunRecordingRequest,
  V1RunRecordingResponse as SdkV1RunRecordingResponse,
  V1Space as SdkV1Space,
  V1SpaceCreateRequest as SdkV1SpaceCreateRequest,
  V1SpaceEnvironment as SdkV1SpaceEnvironment,
  V1SpaceEnvironmentUpdateRequest as SdkV1SpaceEnvironmentUpdateRequest,
  V1SpaceRuntimeCreateRequest as SdkV1SpaceRuntimeCreateRequest,
  V1SpaceUpdateRequest as SdkV1SpaceUpdateRequest,
} from '../../src/index.js';

type Equal<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;
type Assert<T extends true> = T;

type ContractPairs = [
  Assert<Equal<SdkV1Space, V1Space>>,
  Assert<Equal<SdkV1SpaceCreateRequest, V1SpaceCreateRequest>>,
  Assert<Equal<SdkV1SpaceUpdateRequest, V1SpaceUpdateRequest>>,
  Assert<Equal<SdkV1SpaceEnvironment, V1SpaceEnvironment>>,
  Assert<Equal<SdkV1SpaceEnvironmentUpdateRequest, V1SpaceEnvironmentUpdateRequest>>,
  Assert<Equal<SdkV1RuntimeCreateRequest, V1RuntimeCreateRequest>>,
  Assert<Equal<SdkV1SpaceRuntimeCreateRequest, V1SpaceRuntimeCreateRequest>>,
  Assert<Equal<SdkV1RuntimeListQuery, V1RuntimeListQuery>>,
  Assert<Equal<SdkV1Runtime, V1Runtime>>,
  Assert<Equal<SdkV1RuntimeStartResponse, V1RuntimeStartResponse>>,
  Assert<Equal<SdkV1RuntimeRunListQuery, V1RuntimeRunListQuery>>,
  Assert<Equal<SdkV1RuntimeFileCollectRequest, RuntimeFileCollectRequest>>,
  Assert<Equal<SdkV1RuntimeFileStageRequest, V1RuntimeFileStageRequest>>,
  Assert<Equal<SdkV1RuntimeStagedFile, V1RuntimeStagedFile>>,
  Assert<Equal<SdkV1Run, V1Run>>,
  Assert<Equal<SdkV1RunEventsListQuery, V1RunEventsListQuery>>,
  Assert<Equal<SdkV1RunLiveRequest, V1RunLiveRequest>>,
  Assert<Equal<SdkV1RunLiveResponse, V1RunLiveResponse>>,
  Assert<Equal<SdkV1RunRecordingRequest, V1RunRecordingRequest>>,
  Assert<Equal<SdkV1RunRecordingResponse, V1RunRecordingResponse>>,
  Assert<Equal<SdkV1File, V1File>>,
  Assert<Equal<SdkV1FilesListQuery, V1FilesListQuery>>,
  Assert<Equal<SdkV1FileUpdateRequest, V1FileUpdateRequest>>,
  Assert<Equal<SdkV1FileDeleteResponse, V1FileDeleteResponse>>,
  Assert<Equal<SdkV1RunFilesListQuery, V1RunFilesListQuery>>,
  Assert<Equal<SdkV1RunFilesExportRequest, V1RunFilesExportRequest>>,
  Assert<Equal<SdkV1Invocation, V1Invocation>>,
  Assert<Equal<SdkV1InvocationResponse, V1InvocationResponse>>,
  Assert<Equal<SdkV1InvocationSummary, V1InvocationSummary>>,
  Assert<Equal<SdkV1InvocationWaitRequest, V1InvocationWaitRequest>>,
  Assert<Equal<SdkV1InvocationWaitResponse, V1InvocationWaitResponse>>,
  Assert<Equal<SdkV1RunInvocationsListQuery, V1RunInvocationsListQuery>>,
];

export type _SdkV1ContractPairs = ContractPairs;
