import type {
  V1AccountUsage,
  V1AiCredential,
  V1AiCredentialCreateRequest,
  V1AiCredentialDeleteResponse,
  V1AiCredentialListQuery,
  V1AiCredentialTestResponse,
  V1AiCredentialUpdateRequest,
  V1AiModel,
  V1AiModelListQuery,
  V1AiModelListResponse,
  V1AiModelSelection,
  V1AiModelSelectionObject,
  V1AiStoredModelSelection,
  V1ApiKey,
  V1ApiKeyCreateRequest,
  V1ApiKeyCreateResponse,
  V1ApiKeyDeleteResponse,
  V1ApiKeyListQuery,
  V1AuthWhoamiResponse,
  V1BrowserExtension,
  V1BrowserExtensionDeleteResponse,
  V1BrowserExtensionImportRequest,
  V1BrowserExtensionListQuery,
  V1BrowserExtensionUpdateRequest,
  V1File,
  V1FileDeleteResponse,
  V1FileFolder,
  V1FilesListQuery,
  V1FilesListResponse,
  V1FileUpdateRequest,
  V1HelpApiOperation,
  V1HelpAudience,
  V1HelpCliCommand,
  V1HelpExample,
  V1HelpField,
  V1HelpFlag,
  V1HelpIo,
  V1HelpNextStep,
  V1HelpOverviewResponse,
  V1HelpRequest,
  V1HelpResponse,
  V1HelpSdkMethod,
  V1HelpTopic,
  V1HelpTopicResponse,
  V1Invocation,
  V1InvocationResponse,
  V1InvocationSummary,
  V1InvocationWaitRequest,
  V1InvocationWaitResponse,
  V1Proxy,
  V1ProxyCreateRequest,
  V1ProxyDeleteResponse,
  V1ProxyListQuery,
  V1ProxyPool,
  V1ProxyPoolListQuery,
  V1ProxyTestResponse,
  V1ProxyUpdateRequest,
  V1Run,
  V1RunActivityItem,
  V1RunActivityListQuery,
  V1RunEvent,
  V1RunEventsListQuery,
  V1RunFilesExportRequest,
  V1RunFilesListQuery,
  V1RunInvocationsListQuery,
  V1RunLiveRequest,
  V1RunLiveResponse,
  V1RunRecordingRequest,
  V1RunRecordingResponse,
  V1RunSummary,
  V1RunUsage,
  V1Runtime,
  V1RuntimeCreateRequest,
  V1RuntimeFileCollectRequest,
  V1RuntimeFilesListQuery,
  V1RuntimeFileStageRequest,
  V1RuntimeInvocationCreateRequest,
  V1RuntimeStartResponse,
  V1RuntimeStagedFile,
  V1RuntimeStopResponse,
  V1RuntimeTarget,
  V1RuntimeTargetCreateRequest,
  V1RuntimeUpdateRequest,
  V1Space,
  V1SpaceCreateRequest,
  V1SpaceDeleteResponse,
  V1SpaceEnvironment,
  V1SpaceEnvironmentUpdateRequest,
  V1SpaceListQuery,
  V1SpaceUpdateRequest,
  V1Subaccount,
  V1SubaccountArchiveResponse,
  V1SubaccountCreateRequest,
  V1SubaccountGetQuery,
  V1SubaccountLimits,
  V1SubaccountListQuery,
  V1SubaccountUpdateRequest,
  V1SubaccountUsage,
  V1SubaccountUsageListQuery,
  V1SubaccountUsageListResponse,
  V1Tool,
  V1ToolBase,
  V1ToolCall,
  V1ToolCallListQuery,
  V1ToolCallTool,
  V1ToolCreateRequest,
  V1ToolExecutionType,
  V1ToolType,
  V1ToolUpdateRequest,
  V1ToolVersion,
  V1ToolVersionCreateRequest,
  V1Toolset,
  V1ToolsetCreateRequest,
  V1ToolsetDeleteResponse,
  V1ToolsetListQuery,
  V1ToolsetUpdateRequest,
  V1VaultSecret,
  V1VaultSecretDeleteResponse,
  V1VaultSecretListQuery,
  V1VaultSecretPatchRequest,
  V1VaultSecretUpsertRequest,
  V1VaultSecretValue,
  V1VaultTotpResponse,
} from '../../src/index.js';
import type {
  components as OpenApiComponents,
  operations as OpenApiOperations,
} from '../../src/generated/openapi-types.js';

type Equal<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;
type Assert<T extends true> = T;

type OpenApiSchemas = OpenApiComponents['schemas'];
type OpenApiQuery<OperationId extends keyof OpenApiOperations> =
  OpenApiOperations[OperationId] extends { parameters: { query?: infer Query } }
    ? NonNullable<Query>
    : never;

type OpenApiContractPairs = [
  Assert<Equal<V1AuthWhoamiResponse, OpenApiSchemas['AuthWhoamiResponse']>>,
  Assert<Equal<V1ApiKey, OpenApiSchemas['ApiKey']>>,
  Assert<Equal<V1ApiKeyListQuery, OpenApiQuery<'api-keys.list'>>>,
  Assert<Equal<V1ApiKeyCreateRequest, OpenApiSchemas['ApiKeyCreateRequest']>>,
  Assert<Equal<V1ApiKeyCreateResponse, OpenApiSchemas['ApiKeyCreateResponse']>>,
  Assert<Equal<V1ApiKeyDeleteResponse, OpenApiSchemas['ApiKeyDeleteResponse']>>,
  Assert<Equal<V1AccountUsage, OpenApiSchemas['AccountUsage']>>,
  Assert<Equal<V1SubaccountLimits, OpenApiSchemas['SubaccountLimits']>>,
  Assert<Equal<V1Subaccount, OpenApiSchemas['Subaccount']>>,
  Assert<Equal<V1SubaccountListQuery, OpenApiQuery<'subaccounts.list'>>>,
  Assert<Equal<V1SubaccountCreateRequest, OpenApiSchemas['SubaccountCreateRequest']>>,
  Assert<Equal<V1SubaccountUpdateRequest, OpenApiSchemas['SubaccountUpdateRequest']>>,
  Assert<Equal<V1SubaccountGetQuery, OpenApiQuery<'subaccounts.get'>>>,
  Assert<Equal<V1SubaccountArchiveResponse, OpenApiSchemas['SubaccountArchiveResponse']>>,
  Assert<Equal<V1SubaccountUsage, OpenApiSchemas['SubaccountUsage']>>,
  Assert<Equal<V1SubaccountUsageListQuery, OpenApiQuery<'subaccounts.usage.list'>>>,
  Assert<
    Equal<V1SubaccountUsageListResponse, OpenApiSchemas['SubaccountUsageListResponse']>
  >,
  Assert<Equal<V1HelpAudience, NonNullable<OpenApiSchemas['HelpRequest']['audience']>>>,
  Assert<Equal<V1HelpRequest, OpenApiSchemas['HelpRequest']>>,
  Assert<Equal<V1HelpField, OpenApiSchemas['HelpField']>>,
  Assert<Equal<V1HelpFlag, OpenApiSchemas['HelpFlag']>>,
  Assert<Equal<V1HelpIo, OpenApiSchemas['HelpIo']>>,
  Assert<Equal<V1HelpApiOperation, OpenApiSchemas['HelpApiOperation']>>,
  Assert<Equal<V1HelpSdkMethod, OpenApiSchemas['HelpSdkMethod']>>,
  Assert<Equal<V1HelpCliCommand, OpenApiSchemas['HelpCliCommand']>>,
  Assert<Equal<V1HelpExample, OpenApiSchemas['HelpExample']>>,
  Assert<Equal<V1HelpNextStep, OpenApiSchemas['HelpNextStep']>>,
  Assert<Equal<V1HelpTopic, OpenApiSchemas['HelpTopic']>>,
  Assert<Equal<V1HelpOverviewResponse, OpenApiSchemas['HelpOverviewResponse']>>,
  Assert<Equal<V1HelpTopicResponse, OpenApiSchemas['HelpTopicResponse']>>,
  Assert<Equal<V1HelpResponse, OpenApiSchemas['HelpResponse']>>,
  Assert<Equal<V1AiCredential, OpenApiSchemas['AiCredential']>>,
  Assert<Equal<V1AiCredentialListQuery, OpenApiQuery<'ai.credentials.list'>>>,
  Assert<Equal<V1AiCredentialCreateRequest, OpenApiSchemas['AiCredentialCreateRequest']>>,
  Assert<Equal<V1AiCredentialUpdateRequest, OpenApiSchemas['AiCredentialUpdateRequest']>>,
  Assert<Equal<V1AiCredentialDeleteResponse, OpenApiSchemas['AiCredentialDeleteResponse']>>,
  Assert<Equal<V1AiCredentialTestResponse, OpenApiSchemas['AiCredentialTestResponse']>>,
  Assert<Equal<V1AiModel, OpenApiSchemas['AiModel']>>,
  Assert<Equal<V1AiModelListQuery, OpenApiQuery<'ai.models.list'>>>,
  Assert<Equal<V1AiModelListResponse, OpenApiSchemas['AiModelListResponse']>>,
  Assert<Equal<V1AiModelSelectionObject, OpenApiSchemas['AiModelSelection']>>,
  Assert<Equal<V1AiModelSelection, string | OpenApiSchemas['AiModelSelection']>>,
  Assert<Equal<V1AiStoredModelSelection, string | OpenApiSchemas['AiStoredModelSelection']>>,
  Assert<Equal<V1BrowserExtension, OpenApiSchemas['BrowserExtension']>>,
  Assert<Equal<V1BrowserExtensionListQuery, OpenApiQuery<'browser-extensions.list'>>>,
  Assert<
    Equal<V1BrowserExtensionImportRequest, OpenApiSchemas['BrowserExtensionImportRequest']>
  >,
  Assert<
    Equal<V1BrowserExtensionUpdateRequest, OpenApiSchemas['BrowserExtensionUpdateRequest']>
  >,
  Assert<
    Equal<V1BrowserExtensionDeleteResponse, OpenApiSchemas['BrowserExtensionDeleteResponse']>
  >,
  Assert<Equal<V1SpaceListQuery, OpenApiQuery<'spaces.list'>>>,
  Assert<Equal<V1SpaceCreateRequest, OpenApiSchemas['SpaceCreateRequest']>>,
  Assert<Equal<V1SpaceUpdateRequest, OpenApiSchemas['SpaceUpdateRequest']>>,
  Assert<Equal<V1Space, OpenApiSchemas['Space']>>,
  Assert<Equal<V1SpaceDeleteResponse, OpenApiSchemas['SpaceDeleteResponse']>>,
  Assert<Equal<V1SpaceEnvironment, OpenApiSchemas['EnvironmentMountsOutput']>>,
  Assert<
    Equal<V1SpaceEnvironmentUpdateRequest, OpenApiSchemas['SpaceEnvironmentUpdateRequest']>
  >,
  Assert<Equal<V1RuntimeCreateRequest, OpenApiSchemas['RuntimeCreateRequest']>>,
  Assert<Equal<V1RuntimeUpdateRequest, OpenApiSchemas['RuntimeUpdateRequest']>>,
  Assert<Equal<V1Runtime, OpenApiSchemas['Runtime']>>,
  Assert<Equal<V1RuntimeStartResponse, OpenApiSchemas['RuntimeStartResponse']>>,
  Assert<Equal<V1RuntimeStopResponse, OpenApiSchemas['RuntimeStopResponse']>>,
  Assert<Equal<V1RuntimeTarget, OpenApiSchemas['RuntimeTarget']>>,
  Assert<Equal<V1RuntimeTargetCreateRequest, OpenApiSchemas['RuntimeTargetCreateRequest']>>,
  Assert<
    Equal<V1RuntimeInvocationCreateRequest, OpenApiSchemas['RuntimeInvocationCreateRequest']>
  >,
  Assert<Equal<V1Invocation, OpenApiSchemas['Invocation']>>,
  Assert<Equal<V1InvocationResponse, OpenApiSchemas['Invocation']>>,
  Assert<Equal<V1InvocationSummary, OpenApiSchemas['InvocationSummary']>>,
  Assert<Equal<V1InvocationWaitRequest, OpenApiSchemas['InvocationWaitRequest']>>,
  Assert<Equal<V1InvocationWaitResponse, OpenApiSchemas['InvocationWait']>>,
  Assert<Equal<V1RunInvocationsListQuery, OpenApiQuery<'runs.invocations.list'>>>,
  Assert<Equal<V1RunSummary, OpenApiSchemas['RunSummary']>>,
  Assert<Equal<V1Run, OpenApiSchemas['Run']>>,
  Assert<Equal<V1RunUsage, OpenApiSchemas['RunUsage']>>,
  Assert<Equal<V1RunEvent, OpenApiSchemas['RunEvent']>>,
  Assert<Equal<V1RunEventsListQuery, OpenApiQuery<'runs.events.list'>>>,
  Assert<Equal<V1RunActivityItem, OpenApiSchemas['RunActivityItem']>>,
  Assert<Equal<V1RunActivityListQuery, OpenApiQuery<'runs.activity.list'>>>,
  Assert<Equal<V1RunLiveRequest, OpenApiSchemas['RunLiveRequest']>>,
  Assert<Equal<V1RunLiveResponse, OpenApiSchemas['RunLiveResponse']>>,
  Assert<Equal<V1RunRecordingRequest, OpenApiSchemas['RunRecordingRequest']>>,
  Assert<Equal<V1RunRecordingResponse, OpenApiSchemas['RunRecordingResponse']>>,
  Assert<Equal<V1File, OpenApiSchemas['File']>>,
  Assert<Equal<V1FilesListQuery, OpenApiQuery<'files.list'>>>,
  Assert<Equal<V1FilesListResponse, OpenApiSchemas['FileListResponse']>>,
  Assert<Equal<V1FileFolder, OpenApiSchemas['FileFolder']>>,
  Assert<Equal<V1FileUpdateRequest, OpenApiSchemas['FileUpdateRequest']>>,
  Assert<Equal<V1FileDeleteResponse, OpenApiSchemas['FileDeleteResponse']>>,
  Assert<Equal<V1RunFilesListQuery, OpenApiQuery<'runs.files.list'>>>,
  Assert<Equal<V1RunFilesExportRequest, OpenApiSchemas['RunsFilesExportRequest']>>,
  Assert<Equal<V1RuntimeFilesListQuery, OpenApiQuery<'runtimes.files.list'>>>,
  Assert<Equal<V1RuntimeFileStageRequest, OpenApiSchemas['RuntimeFileStageRequest']>>,
  Assert<Equal<V1RuntimeStagedFile, OpenApiSchemas['RuntimeStagedFile']>>,
  Assert<Equal<V1RuntimeFileCollectRequest, OpenApiSchemas['RuntimeFileCollectRequest']>>,
  Assert<Equal<V1Proxy, OpenApiSchemas['Proxy']>>,
  Assert<Equal<V1ProxyCreateRequest, OpenApiSchemas['ProxyCreateRequest']>>,
  Assert<Equal<V1ProxyUpdateRequest, OpenApiSchemas['ProxyUpdateRequest']>>,
  Assert<Equal<V1ProxyListQuery, OpenApiQuery<'proxies.list'>>>,
  Assert<Equal<V1ProxyDeleteResponse, OpenApiSchemas['ProxyDeleteResponse']>>,
  Assert<Equal<V1ProxyTestResponse, OpenApiSchemas['ProxyTestResponse']>>,
  Assert<Equal<V1ProxyPool, OpenApiSchemas['ProxyPool']>>,
  Assert<Equal<V1ProxyPoolListQuery, OpenApiQuery<'proxies.pools.list'>>>,
  Assert<Equal<V1ToolExecutionType, OpenApiSchemas['ToolCallTool']['executionType']>>,
  Assert<Equal<V1ToolType, OpenApiSchemas['Tool']['type']>>,
  Assert<
    Equal<
      V1ToolBase,
      Pick<
        OpenApiSchemas['BuiltinTool'],
        | 'id'
        | 'spaceId'
        | 'name'
        | 'description'
        | 'inputSchema'
        | 'outputSchema'
        | 'status'
        | 'metadata'
        | 'createdAt'
        | 'updatedAt'
      >
    >
  >,
  Assert<Equal<V1Tool, OpenApiSchemas['Tool']>>,
  Assert<Equal<V1ToolCreateRequest, OpenApiSchemas['ToolCreateRequest']>>,
  Assert<Equal<V1ToolUpdateRequest, OpenApiSchemas['ToolUpdateRequest']>>,
  Assert<Equal<V1ToolVersion, OpenApiSchemas['ToolVersion']>>,
  Assert<Equal<V1ToolVersionCreateRequest, OpenApiSchemas['ToolVersionCreateRequest']>>,
  Assert<Equal<V1ToolCall, OpenApiSchemas['ToolCall']>>,
  Assert<Equal<V1ToolCallTool, OpenApiSchemas['ToolCallTool']>>,
  Assert<Equal<V1ToolCallListQuery, OpenApiQuery<'tool-calls.list'>>>,
  Assert<Equal<V1Toolset, OpenApiSchemas['Toolset']>>,
  Assert<Equal<V1ToolsetListQuery, OpenApiQuery<'toolsets.list'>>>,
  Assert<Equal<V1ToolsetCreateRequest, OpenApiSchemas['ToolsetCreateRequest']>>,
  Assert<Equal<V1ToolsetUpdateRequest, OpenApiSchemas['ToolsetUpdateRequest']>>,
  Assert<Equal<V1ToolsetDeleteResponse, OpenApiSchemas['ToolsetDeleteResponse']>>,
  Assert<Equal<V1VaultSecret, OpenApiSchemas['VaultSecret']>>,
  Assert<Equal<V1VaultSecretListQuery, OpenApiQuery<'vault.secrets.list'>>>,
  Assert<Equal<V1VaultSecretUpsertRequest, OpenApiSchemas['VaultSecretUpsertRequest']>>,
  Assert<Equal<V1VaultSecretPatchRequest, OpenApiSchemas['VaultSecretPatchRequest']>>,
  Assert<Equal<V1VaultSecretValue, OpenApiSchemas['VaultSecretValue']>>,
  Assert<Equal<V1VaultTotpResponse, OpenApiSchemas['VaultTotpResponse']>>,
  Assert<Equal<V1VaultSecretDeleteResponse, OpenApiSchemas['VaultSecretDeleteResponse']>>,
];

export type _SdkV1OpenApiContractPairs = OpenApiContractPairs;
